//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.2 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2025.07.02 at 12:42:15 PM WEST 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://soap.example.com/pret", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package com.example.soap.pret;
